### ISSUE TITLE
Delete VMT Renaming Section of PCC Guide

### ISSUE THREAD

**Issue by McGravel** [momentum-mod/docs#104]
~~The [Materials Section](https://docs.momentum-mod.org/guide/parallax-corrected-cubemaps/#materials) of the Parallax-Corrected Cubemaps page may benefit from a [link to my tool](https://github.com/McGravel/Parallax-Cubemap-VMT-Tool/releases/tag/0.6) for making such a process somewhat easier.~~

This section is not needed, so it should be removed instead it seems.

**Comment by Gocnak** [comment]
This might not be needed anymore due to our shader overriding.
