### ISSUE TITLE
Rename momentum entities moving to base engine (remove `_momentum_` part)

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/docs#199]
Entities are moving to the base engine for all of Chaos to enjoy, so we should move away from the momentum names for these entities. While the ent name will still work with `_momentum_` in it, it is only due to backwards compat.

**Comment by hexaflexahexagon** [comment]
A list of all the pages that need this change would make this issue much easier for a non-developer to do

**Comment by braem** [comment]
> 
> 
> A list of all the pages that need this change would make this issue much easier for a non-developer to do

These are:
- `env_momentum_surface_teleport` -> `env_surface_teleport`
- `filter_momentum_velocity` -> `filter_velocity`
- `trigger_momentum_catapult` -> `trigger_catapult`
- `trigger_momentum_setspeed` -> `trigger_setspeed`
- `trigger_momentum_reversespeed` -> `trigger_reversespeed`
- `trigger_momentum_userinput` -> `trigger_userinput`

Don't think we're thinking about baselining any more in the near future (maybe push trigger), though would be nice to get more of them in base engine
