### ISSUE TITLE
Missing step in building guide for windows 

### ISSUE THREAD

**Issue by Ulti-FD** [momentum-mod/docs#21]
**File:** _posts/2019-09-10-guide_building_the_game.md

Building in Windows requires the C++ Desktop component ([this](https://cdn.discordapp.com/attachments/235111289435717633/631543356924624896/unknown.png)) which is not mentioned in the steps. It may also require other components as I installed a few other extra things, so it might be a good idea to double check all that.

Also what's with [this](https://github.com/momentum-mod/game/wiki)? Found this page before finding the docs site and it led me to think you still need a key to play the latest ver. Might as well trash it now that you have an actual (and recent) wiki.

**Comment by Gocnak** [comment]
This has since been fixed via #39
