### ISSUE TITLE
Document the rank points and cosmetic XP systems

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/docs#255]
It'd be great to convert the ranking system document into markdown: https://docs.google.com/document/d/1Zj8FKrfAMqYSnAHjySJqoqq0vmAEWxYXVcYLi3_u7NA/edit

And to convert/link to the cosmetic XP table to markdown: https://docs.google.com/spreadsheets/d/1JiHJYsxlGPXAZqCPh7-paJI6U_TH-Ro0H0OWDFCiA74/edit#gid=0

They can be under one page but two sections.

**Comment by antjlo** [comment]
Does the font matter at all? I'm down to convert it

**Comment by antjlo** [comment]
`They can be under one page but two sections.` Also do you mean in one markdown file?
so a h1 for the ranking info and a h1 for the xp table? or in seperate files

**Comment by antjlo** [comment]
In either case I have managed to make this, I am not a pro at markdown so you should give it a look [ranking.md](https://github.com/momentum-mod/docs/files/7974698/ranking.md)

**Comment by braem** [comment]
Closed by #257
