### ISSUE TITLE
update movement cvars

### ISSUE THREAD

**Issue by braem** [momentum-mod/docs#272]
With the movement refactor comes a change to essentially all movement cvars to be under `mom_mv_*`. These wont directly translate as some cvars were split into multiple ones.

-------------------------------
From @jason-e 's internal PR:

## New cvars
- `mom_mv_use_old_gamemovement`: Togglable cvar for switching back to old movement code. Will be removed in the future upon squashing all bugs with the new movement code.
- `mom_mv_fix_duck_transitions`: Handles ducking transitions better when abruptly changing duck direction (e.g. releasing the duck key after starting a duck transition but before being fully ducked) -- also now implemented for all modes
- `mom_mv_fix_duck_key_desync`: Ensures that duck state reflects whether the duck key is down or not, rather than only reacting to the key having just been pressed or released. This fixes disjoint behavior when duck state is forcibly changed, for example when loading a saveloc. This previously only fixed situations where the player is forcibly unducked, but now also handles being forcibly ducked as well. -- also now implemented for all modes
- `mom_mv_key_movement_ignores_roll`: Ignores view roll angle when determining the "wish direction" for applying force imposed by movement keys (e.g. +moveleft). This fixes accidental counter-strafing when being rolled by a portal.
- `mom_mv_ladder_edge_grabbing`: Enables automatically grabbing ladders by walking off an edge above them (using CSGO's implementation as the CS:S one is buggy). I made this a ConVar as I'm not sure if it's right for Conc to have this behavior or not.
- `mom_mv_normalize_jump_height`: (currently CS:S modes only) Ensures jump height is exactly the same every time, regardless of whether the player is ducked or how many times the player has bhopped in a row. The height is affected by mom_mv_jump_z_offset which is currently 1.5 units -- this is probably the "correct" value for bhop but it should be derived from the tickrate, something that needs to be figured out later.
- `mom_mv_disable_impact_view_punch`: Disables CS:S-like view punch (camera roll) when hitting something with enough speed
- `mom_mv_fix_nojump_slope_boosts`: Fixes the behavior where the player is given extra z velocity essentially for free when quickly moving up an incline during ground movement -- typically abused by hitting a slope at high speed in the air but without holding jump and with the "uphill RNG" fix enabled (`mom_mv_fix_uphill_slopes`). This bug is sometimes attributed to the uphill RNG fix but it is actually just part of the game. This fix also used to be grouped under `sv_rngfix_enable` but is now separate.
- `mom_mv_allow_zero_gravity`: Allows the player to actually experience zero gravity when the player entity's local gravity scale is set to zero. Normally, a zero gravity scale is interpreted as a scale of 1.0. This feature is still off for SJ/RJ, though I'm wondering if it should be on (or even off) for all modes.

## Renamed and functionally changed cvars
- `mom_mv_fix_trigger_jumping`: The fix for landing above thin triggers on the ground (previously part of `sv_ground_trigger_fix`)
- `mom_mv_fix_unduck_instant_land`: The fix for unducking and landing in the same tick, before movement occurs, aka duckbug/jumpbug (previously part of `sv_ground_trigger_fix` as well). I also switched to a much much cleaner implementation of this fix which exists right within the movement code and only takes a few lines of code for a precise implementation, whereas the old version was a lot of code and somewhat of an approximation.
- `mom_mv_considered_on_ground`: The maximum distance from the ground that the player is considered touching it. This is naturally 2.0 units in Source games, and while Momentum had changed this to 1.0 on most modes, I've changed this back to 2.0 on all modes as I think it really just partially reduces a variety of undesired behaviors. These behaviors are likely all resolved by other changes by now, and any that aren't should be fixed more directly.
- `mom_mv_fix_downhill_slopes`: Previously `sv_slope_fix` -- this fix had different (but kind of identical?) implementations depending on if `sv_rngfix_enable` was on, but this has been refactored to be just one implementation.
- `mom_mv_fix_uphill_slopes`: Previously `sv_slope_fix` + `sv_rngfix_enable` -- This is still only on for bhop, but we need to figure out which other modes want this (probably many of them since it is an RNG fix after all).

## Removed
- `sv_rngfix_enable`/`sv_slope_fix`: Previously determined a few different behaviors but this has effectively been replaced by the changes described above. (Note this ConVar and `sv_slope_fix` temporarily still exist for use in the old movement code, but can be removed from docs)

## Renamed only from sv_* (no functional change)
- `mom_mv_fix_duck_collision`
- `mom_mv_fix_edges`
- `mom_mv_jump_z_offset`
- `mom_mv_fix_ramp_bugs`
- `mom_mv_ramp_bumpcount`
- `mom_mv_ramp_initial_retrace_length`

**Comment by tmob03** [comment]
Are all of these variables, 0 and 1? I’ll add them when I know.

**Comment by tmob03** [comment]
Never mind, I can check them myself.
