### ISSUE TITLE
Guide to override assets (using custom/ folder)

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/docs#30]
For custom HUDs, weapons, etc, players can use their `custom/` folder. The game will be shipping some TF2 weapon scripts as examples of overrides. A guide on how to use them to override the momentum specific stuff would be good.

**Comment by braem** [comment]
Is this essentially moving the [readme in the game repo](https://github.com/momentum-mod/game/blob/develop/mp/game/momentum/custom/readme.txt) to the docs page?

**Comment by Gocnak** [comment]
Yeah, but with an example of changing the weapon script, for example.
