### ISSUE TITLE
Port project to Hugo

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/docs#313]
After evaluating Hugo for the blog, I think it's fair to say that we should move this docs site over to using it now to simplify our knowledge requirements and tech stack.

- [x] Find a theme that fits the current requirements of the docs site
- [x] Merge all existing work into main branch
- [x] Port to new theme under Hugo
- [x] Ensure everything works fine
- [x] Update readme with new setup instructions
- [x] Update "how to create a docs page" page with new setup / posting instructions / commands
- [x] Update Cloudflare Pages job info to use Hugo

**Comment by hexaflexahexagon** [comment]
BOOM
