### ISSUE TITLE
Parkour gamemode vars

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/docs#58]
https://github.com/momentum-mod/game/pull/841

There's a lot of vars that will eventually become hardcoded as the movement gets perfected, but there are things like camera tilt or whatnot that can stay as customizable.

**Comment by braem** [comment]
I can throw up a PR for this, though which cvars should we document? I could do all then update that once the gamemode is fully functional.

**Comment by Gocnak** [comment]
Eh, to save work I would wait until we get the fzzy code merged in.
