### ISSUE TITLE
Update linux build steps with netbeans stuff

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/docs#64]
https://github.com/momentum-mod/game/pull/894/

~Also update MomentumDev zip link with new link: https://drive.google.com/file/d/1HD1Mh8JrCBqP2sh8WJCpfybJGI4BPcZ4/view?usp=sharing~ This is now included in the site.

**Comment by chrb22** [comment]
I also have this for Linux: https://drive.google.com/file/d/1tF7Bh6tp3YjaFj2PxybMoPnsavRKAJRK/view
