### ISSUE TITLE
trigger_momentum_catapult documentation

### ISSUE THREAD

**Issue by notbad69** [momentum-mod/docs#79]
momentum-mod/game#926

# trigger_momentum_catapult
## Abstract
A trigger volume that launches the player at a specified target or in a specified direction at a specified speed. This entity also contains some filtering for the players velocity and entry angle.

## Keyvalues
* Player Speed: The base speed to launch the player at in u/sec
* Use Threshold Check[DEPRECATED]: Turns on the filtering based on players speed and entry angle when interacting with the entity. (Prefer using filter_momentum_velocity for this functionality)
* Entry Angle Tolerance: The player's velocity must be pointing this much at the target for the entity to fire. Specify a value between [-1...1] 1 means exactly, 0 means within 180 degrees -1 means any angle is accepted. This is only used if Use Threshold Check is set to yes.
* Use Exact Velocity: Try to launch the player at the exact speed specified in Player Speed. This does not guarantee a valid solution (i.e. the speed is set too low) so it will fall back to the non-exact case which does guarantee a solution.
* Exact Solution Method: Choice determining the launch direction for the exact velocity option, as there will be two valid solutions given that there is at least one 
    * Best: This option will minimize the players entry angle with respect to the launch velocity direction
    * Solution One; Selects the lower angle
    * Solution Two: Selects the higher angle
* Lower Threshold: Flung player must be within this percentage value in order to activate fling. Specify a value between [0...1] (default is .15) This is only used if Use Threshold Check is set to yes.
* Upper Threshold: Flung player must be within this percentage value in order to activate fling. Specify a value between [0...1] (default is .30) This is only used if Use Threshold Check is set to yes.
* Launch Direction: Direction to launch the player in. (If porting from tf2 using this option and it is set to exactly vertical, you need to multiply the Player Speed by 1.5)
* Launch Target: Entity to try to 'hit' when we're launched
* Only check velocity[DEPRECATED]: Only check velocity of the touching object - don't actually catapult it.  Use in conjunction with OnCatapulted to create velocity checking triggers.  Only works when Use Threshold Check is enabled. (Prefer using filter_momentum_velocity for this functionality)
* OnThink: Refire entity on an interval set by Interval
* Interval: Time in seconds between updates when OnThink is set to 1
* Every Tick: Refires the entity every tick while the player is touching
* Height Offset: Offsets (in u) the origin of the player (Legacy value is 32u from TF2)

## Outputs
* OnCatapulted: Fired when the player is successfully launched or when it passes filters for Only Check Velocity

**Comment by braem** [comment]
Considering this seems already written, are you planning on doing a PR for this? If not I can do it and add you as a co-author.

**Comment by notbad69** [comment]
You can go ahead and make it, that would be great.
