### ISSUE TITLE
Document func_nogrenades' "fizzle immediately" property

### ISSUE THREAD

**Issue by braem** [momentum-mod/docs#81]
Tackle this only after https://github.com/momentum-mod/game/issues/957 is complete.

**Comment by braem** [comment]
Are you planning on documenting this @ijre ? I can do if not.

**Comment by ijre** [comment]
It would be greatly appreciated if you did; I totally forgot that one would have to document it here as it's an entity, and I have no idea where to begin within the repo for making the new page; sorry about that

**Comment by braem** [comment]
No worries; only requirement is that you make the issue if you create a PR that changes/add/removes an entity/cvar/ccommand, but I had already made it. Just didn't want to step on your toes :)
